In [8]:
# 涉及到数组的重量级运算操作，可以使用 NumPy 库。 
# NumPy 的一个主要特征是它会给Python提供一个数组对象，相比标准的Python列表而已更适合用来做数学运算。 
# 下面是一个简单的小例子，向你展示标准列表对象和 NumPy 数组对象之间的差别：

x = [1, 2, 3, 4]
y = [5, 6, 7, 8]
x * 2


[1, 2, 3, 4, 1, 2, 3, 4]

In [3]:
x + 10

TypeError: can only concatenate list (not "int") to list

In [7]:
x + y

[1, 2, 3, 4, 5, 6, 7, 8]

In [9]:
# Numpy数组
import numpy as np

ax = np.array([1, 2, 3, 4])
ay = np.array([5, 6, 7, 8])
ax * 2


array([2, 4, 6, 8])

In [10]:
ax +10 

array([11, 12, 13, 14])

In [11]:
ax + ay


array([ 6,  8, 10, 12])

In [12]:
ax * ay

array([ 5, 12, 21, 32])

In [13]:
# 正如所见，两种方案中数组的基本数学运算结果并不相同。 
# 特别的， NumPy 中的标量运算(比如 ax * 2 或 ax + 10 )会作用在每一个元素上。 
# 另外，当两个操作数都是数组的时候执行元素对等位置计算，并最终生成一个新的数组。


In [15]:
# 数组不对等情况(会报错)
aa = np.array([1, 3, 4])
ab = np.array([2, 3, 4, 5])
aa * ab

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [16]:
# 正如所见，两种方案中数组的基本数学运算结果并不相同。 特别的， NumPy 中的标量运算(比如 ax * 2 或 ax + 10 )会作用在每一个元素上。 
# 另外，当两个操作数都是数组的时候执行元素对等位置计算，并最终生成一个新的数组。


def f(x):
    return 3 * x ** 2 - 2 * x + 7

f(ax)


array([ 8, 15, 28, 47])

In [17]:
#  NumPy 还为数组操作提供了大量的通用函数，这些函数可以作为 math 模块中类似函数的替代
np.sqrt(ax)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [18]:
np.cos(ax)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [19]:
# 使用这些通用函数要比循环数组并使用 math 模块中的函数执行计算要快的多。 
# 因此，只要有可能的话尽量选择 NumPy 的数组方案。

底层实现中， NumPy 数组使用了C或者Fortran语言的机制分配内存。 也就是说，它们是一个非常大的连续的并由同类型数据组成的内存区域。 所以，你可以构造一个比普通Python列表大的多的数组。 比如，如果你想构造一个10,000*10,000的浮点数二维网格，很轻松：

In [20]:
grid = np.zeros(shape=(10000, 10000), dtype=float)
grid


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [22]:
grid += 10
grid


array([[20., 20., 20., ..., 20., 20., 20.],
       [20., 20., 20., ..., 20., 20., 20.],
       [20., 20., 20., ..., 20., 20., 20.],
       ...,
       [20., 20., 20., ..., 20., 20., 20.],
       [20., 20., 20., ..., 20., 20., 20.],
       [20., 20., 20., ..., 20., 20., 20.]])

In [23]:
np.sin(grid)

array([[0.91294525, 0.91294525, 0.91294525, ..., 0.91294525, 0.91294525,
        0.91294525],
       [0.91294525, 0.91294525, 0.91294525, ..., 0.91294525, 0.91294525,
        0.91294525],
       [0.91294525, 0.91294525, 0.91294525, ..., 0.91294525, 0.91294525,
        0.91294525],
       ...,
       [0.91294525, 0.91294525, 0.91294525, ..., 0.91294525, 0.91294525,
        0.91294525],
       [0.91294525, 0.91294525, 0.91294525, ..., 0.91294525, 0.91294525,
        0.91294525],
       [0.91294525, 0.91294525, 0.91294525, ..., 0.91294525, 0.91294525,
        0.91294525]])

In [24]:
# 关于 NumPy 有一点需要特别的主意，那就是它扩展Python列表的索引功能 - 特别是对于多维数组。
#  为了说明清楚，先构造一个简单的二维数组并试着做些试验：

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
# 维度
a.ndim

2

In [27]:
a.shape

(3, 4)

In [28]:
a[0]

array([1, 2, 3, 4])

In [29]:
# column 1
a[:, 1]

array([ 2,  6, 10])