问题：你需要执行矩阵和线性代数运算，比如矩阵乘法、寻找行列式、求解线性方程组等等。

In [1]:
import numpy as np

m = np.matrix([[1, -2, 3], [0, 4, 5], [7, 8, -9]])
m


matrix([[ 1, -2,  3],
        [ 0,  4,  5],
        [ 7,  8, -9]])

In [2]:
# 转置
m.T

matrix([[ 1,  0,  7],
        [-2,  4,  8],
        [ 3,  5, -9]])

In [3]:
# 求逆矩阵
m.I

matrix([[ 0.33043478, -0.02608696,  0.09565217],
        [-0.15217391,  0.13043478,  0.02173913],
        [ 0.12173913,  0.09565217, -0.0173913 ]])

In [5]:
# 矩阵乘法
v = np.matrix([[2], [3], [4]])
v


matrix([[2],
        [3],
        [4]])

In [6]:
m * v

matrix([[ 8],
        [32],
        [ 2]])

In [8]:
# 可以在 numpy.linalg 子包中找到更多的操作函数，比如：
import numpy.linalg

# det A,A的行列式
numpy.linalg.det(m)

-229.99999999999983

In [9]:
# 特征值Eigenvalues
numpy.linalg.eigvals(m)


array([-13.11474312,   2.75956154,   6.35518158])

In [10]:
# Solve for x in mx = v
x = numpy.linalg.solve(m, v)
x


matrix([[0.96521739],
        [0.17391304],
        [0.46086957]])

In [11]:
m * x

matrix([[2.],
        [3.],
        [4.]])

In [12]:
v

matrix([[2],
        [3],
        [4]])